version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "pipeline-docker-auth:username"
    SECRET_PASSWORD: "pipeline-docker-auth:password"

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Registry"
      - echo "$SECRET_PASSWORD" | docker login -u "$SECRET_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t vikkapoor25/arsenal-db:latest .

  post_build:
    commands:
      - echo "Pushing Docker Image..."
      - docker push vikkapoor25/arsenal-db:latest

artifacts:
  files:
    - Dockerfile
